services:
  - name: openiddictserver
    port: 8080
  - name: identityserver
    port: 8080
  - name: argocd-server
    namespace: argocd
    subdomain: argocd
  - name: argocd-server
    namespace: argocd
    subdomain: argocd
  - name: keycloak
    serviceName: keycloak-keycloakx-http
    annotations:
      nginx.ingress.kubernetes.io/app-root: /auth/
  # - name: grafana
  #   namespace: monitoring
  #   serviceName: kube-prometheus-stack-grafana
  # - name: prometheus
  #   namespace: monitoring
  #   subdomain: prometheus
  #   serviceName: kube-prometheus-stack-prometheus
  #   port: 9090
  # - name: pgadmin
  #   serviceName: pgadmin-pgadmin4
