global:
  env: dta


helmCharts:
  keycloak:
    enabled: false

  airflow:
    enabled: false

  helm-guestbook:
    enabled: true
    name: helm-guestbook
    namespace: guestbook

  sealed-secrets:
    enabled: true

  nginx-ingress:
    enabled: true

  kube-prometheus-stack:
    enabled: false

  loki:
    enabled: false

  promtail:
    enabled: false

  harbor:
    enabled: false

  cert-manager:
    enabled: false

  actions-runner-controller:
    enabled: false

  actions-runner:
    enabled: false
