global:
  env: dta

applications:
  # A Kustomize application
  hello:
    enabled: true
    path: values/hello/overlays/dta

  # Raw manifests
  raw:
    enabled: true
    path: apps/raw/dta

  # Database clusters (raw manifests)
  cnpg-database:
    enabled: false
    path: apps/cnpg-database/dta

helmCharts:
  keycloak:
    enabled: true

  actions-runner-controller:
    enabled: false

  actions-runner:
    enabled: false

  kube-prometheus-stack:
    enabled: false

  loki:
    enabled: false

  promtail:
    enabled: false

  cert-manager:
    enabled: false

  cloudnative-pg:
    enabled: true

  ingress-nginx:
    enabled: true
