applications:
  cnpg-database:
    enabled: true

helmCharts:
  keycloak:
    enabled: true

  ingress-nginx:
    enabled: true

  kube-prometheus-stack:
    enabled: true

  loki:
    enabled: true

  promtail:
    enabled: true

  cloudnative-pg:
    enabled: true

  cert-manager:
    enabled: true

  backstage:
    enabled: true

  gitea:
    enabled: false

  harbor:
    enabled: false

  # Microservice helm charts for the dev environment

  todolist-frontend-dev:
    enabled: true
    values: microservices-kind/dev/todolist/frontend/values.yaml

  show-env-dev:
    enabled: true
    values: microservices-kind/dev/show-env/values.yaml

# Microservice helm charts for the tst environment

  todolist-frontend-tst:
    enabled: true
    values: microservices-kind/tst/todolist/frontend/values.yaml


# Microservice helm charts for the prd environment

  todolist-frontend-prd:
    enabled: true
    values: microservices-kind/prd/todolist/frontend/values.yaml
