applications:
  cnpg-database:
    enabled: true

helmCharts:
  keycloak:
    enabled: true

  ingress-nginx:
    enabled: true

  kube-prometheus-stack:
    enabled: true

  loki:
    enabled: true

  promtail:
    enabled: true

  cloudnative-pg:
    enabled: true

  todolist-frontend-dev:
    enabled: true

  todolist-frontend-tst:
    enabled: true

  todolist-frontend-prd:
    enabled: true

  show-env-dev:
    enabled: true

  guestbook-dev:
    enabled: true
