ArgocdApplications:

  #=================================#
  #      Platform Tools             #
  #=================================#

  keycloak:
    enabled: false
    syncWave: 1

  keycloak-operator:
    enabled: false
    syncWave: 1

  cert-manager:
    enabled: false

  external-secrets:
    enabled: false

  dashboards:
    enabled: false
    syncWave: 2

  loki:
    enabled: false
    syncWave: 2

  promtail:
    enabled: false
    syncWave: 2

  opencost:
    enabled: false
    syncWave: 1

  #=================================#
  #      Developer Applications     #
  #=================================#

  grpc-server:
    enabled: false

  show-env:
    enabled: false

  frontend-https:
    enabled: false
    syncWave: 1

  backend:
    enabled: false
