services:
  - name: argocd-server
    namespace: argocd
    subdomain: argocd
    ingressClassName: external-nginx
  # - name: backstage
  #   port: 7007
  #   ingressClassName: external-nginx
  - name: keycloak
    serviceName: keycloak-keycloakx-http
    annotations:
      nginx.ingress.kubernetes.io/app-root: /auth/
    ingressClassName: external-nginx
  - name: grafana
    namespace: monitoring
    serviceName: kube-prometheus-stack-grafana
    ingressClassName: external-nginx
  - name: prometheus
    namespace: monitoring
    subdomain: prometheus
    serviceName: kube-prometheus-stack-prometheus
    port: 9090
    ingressClassName: external-nginx
  - name: pgadmin
    serviceName: pgadmin-pgadmin4
    ingressClassName: external-nginx
  - name: show-env-dev
    ingressClassName: external-nginx
  - name: echo
    port: 8080
