useHttps: false

replicaCount: 1

image:
  repository: ghcr.io/maartenvanwersch/price-peek
  tag: main

containerPorts:
  http: 8080

service:
  type: ClusterIP
  ports:
    http: 8080

# ingress:
#   enabled: true
#   className: nginx-internal
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#   hosts:
#     - host: kuberise.internal
#       paths:
#         - path: /backend
#           pathType: Prefix
#   tls: []

env:
  PORT: 8080
  GO_ENV: production
  CORS_ALLOWED_ORIGINS: *
  PROJECT_ID: suio-moneyys-prod
  GIN_MODE: release
  VERTEX_AI_LOCATION: us-central1
  GOOGLE_APPLICATION_CREDENTIALS: /service-account.json

imagePullSecrets:
  - name: ghcr-secret
