{{- range .Values.services }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ default .name .namespace }}
spec:
  ingressClassName: {{ default "nginx" .ingressClassName }}
  rules:
  - host: {{ default .name .subdomain }}.{{ $.Values.global.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ default .name .serviceName }}
            port:
              number: {{ default 80 .port }}
        path: {{ default "/"" .path }}
        pathType: Prefix
  tls:
  - hosts:
    - {{ .subdomain }}.{{ $.Values.global.domain }}
---
{{- end }}

# TODO: if there is secretname add the secret name to the tls section
