keycloak:

  externalDatabase:
    host: cnpg-database-rw.cloudnative-pg.svc.cluster.local
    user: app
    database: app
    existingSecret: pg-secret
    existingSecretPasswordKey: password

  auth:
    adminUser: admin
    existingSecret: pg-secret
    passwordSecretKey: password

  tls:
    enabled: false

  production: false

  ingress:
    enabled: true
    ingressClassName: "nginx"
    tls: false
    hostname: keycloak-127-0-0-1.nip.io
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      cert-manager.io/cluster-issuer: "ca-clusterissuer"
    extraTls:
    - hosts:
      - "*.nip.io"
      secretName: wildcard-cert-tls
