expose:
  type: ingress
  ingress:
    tls:
    - hosts:
      - "*.nip.io"
      secretName: wildcard-cert-tls
    hosts:
      core: core.harbor-127-0-0-1.nip.io
      notary: notary.harbor-127-0-0-1.nip.io
    className: nginx
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      cert-manager.io/cluster-issuer: "ca-clusterissuer"
externalURL: http://core.harbor-127-0-0-1.nip.io
