controller:
  watchIngressWithoutClass: false
  service:
    annotations:
      external-dns.alpha.kubernetes.io/internal-hostname: kuberise.internal
      external-dns.alpha.kubernetes.io/access: private
      external-dns.alpha.kubernetes.io/owner: private-dns
  image:
    registry: registry:5000
    image: ingress-nginx/controller
    tag: "v1.9.6"
    digest: ""
    digestChroot: ""
