replicaCount: 1

ingress:
  enabled: true
  className: external-nginx
  annotations:
    cert-manager.io/cluster-issuer: http-01-production
  hosts:
    - host: show-env.eks.kuberise.dev
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  Environment: dev
  name: env-show
  PROTOCOL: HTTP

image:
  tag: latest
