image:
  repository: nginx
  tag: alpine

useHttps: true

containerPorts:
  https: 8443

service:
  type: ClusterIP
  ports:
    https: 443

ingress:
  className: nginx-external
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "selfsigned"
  tls:
    - secretName: "frontend-https-tls"
      hosts:
        - '{{ include "generic-deployment.fullname" . }}.{{ $.Values.global.domain }}'

config:
  mountPath: /etc/nginx/conf.d
  data:
    default.conf: |
      server {
        listen 8443 ssl;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        ssl_trusted_certificate /etc/nginx/certs/ca.crt;

        location / {
          root /usr/share/nginx/html;
          index index.html;
        }

        error_page 403 404 500 502 503 504 /custom_50x.html;
      }

      server {
        listen 80;
        return 301 https://$host$request_uri;
      }

volumes:
- name: tls-cert
  secret:
    secretName: frontend-https-tls

volumeMounts:
- name: tls-cert
  mountPath: /etc/nginx/certs
  readOnly: true

# sample https probes
livenessProbe:
  httpGet:
    path: /
    port: https
    scheme: HTTPS
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /
    port: https
    scheme: HTTPS
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
startupProbe:
  httpGet:
    path: /
    port: https
    scheme: HTTPS
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 30
