apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin
  namespace: pgadmin
data:
  config_local.py: |-
    import os
    import logging

    FILE_LOG_LEVEL = logging.INFO
    SERVER_MODE = True
    CONSOLE_LOG_LEVEL = logging.INFO
    MASTER_PASSWORD_REQUIRED = False
    AUTHENTICATION_SOURCES = ['internal', 'oauth2']
    OAUTH2_CONFIG = [
      {
        'OAUTH2_NAME': 'Keycloak',
        'OAUTH2_DISPLAY_NAME': 'Keycloak',
        'OAUTH2_ICON': 'fa-key',
        'OAUTH2_CLIENT_ID': 'pgadmin',
        'OAUTH2_CLIENT_SECRET': 'put-your-client-secret-here',
        'OAUTH2_TOKEN_URL': 'https://keycloak.aks.kuberise.dev/auth/realms/platform/protocol/openid-connect/token',
        'OAUTH2_AUTHORIZATION_URL': 'https://keycloak.aks.kuberise.dev/auth/realms/platform/protocol/openid-connect/auth',
        'OAUTH2_API_BASE_URL': 'https://keycloak.aks.kuberise.dev/auth/',
        'OAUTH2_USERINFO_ENDPOINT': 'https://keycloak.aks.kuberise.dev/auth/realms/platform/protocol/openid-connect/userinfo',
        'OAUTH2_SERVER_METADATA_URL': 'https://keycloak.aks.kuberise.dev/auth/realms/platform/.well-known/openid-configuration',
        'OAUTH2_LOGOUT_URL': 'https://keycloak.aks.kuberise.dev/auth/realms/platform/protocol/openid-connect/logout?client_id=pgadmin',
        'OAUTH2_SCOPE': 'openid email profile',
        'OAUTH2_USERNAME_CLAIM': None,
        'OAUTH2_BUTTON_COLOR': '#f44242',
        'OAUTH2_SSL_CERT_VERIFICATION': False,

      }
    ]
