replicaCount: 1

ingress:
  enabled: true
  annotations:
      cert-manager.io/cluster-issuer: "ca-clusterissuer-external"
  tls:
  - hosts:
    - "show-env-dev.kind.kuberise.dev"
    secretName: wildcard-cert-tls
  hosts:
    - host: show-env-dev.kind.kuberise.dev
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  Environment: dev
  name: env-show
  PROTOCOL: HTTP

image:
  repository: ghcr.io/kuberise/show-env
  tag: latest
