replicaCount: 1

ingress:
  enabled: true
  className: external-nginx
  annotations:
      cert-manager.io/cluster-issuer: http-01-production
  tls:
  - hosts:
    - "*.eks.kuberise.dev"
    secretName: wildcard-cert-tls
  hosts:
    - host: frontend-dev.eks.kuberise.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
