replicaCount: 1

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: ca-clusterissuer
  hosts:
    - host: show-env.dev.172.19.0.5.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  Environment: dev
  name: env-show
  PROTOCOL: HTTP

image:
  tag: latest
