prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        app.kubernetes.io/part-of: kube-prometheus-stack
    serviceMonitorNamespaceSelector:
      matchLabels:
        monitoring: prometheus
