k8sServiceHost: ""
k8sServicePort: "6443"
kubeProxyReplacement: "false"

bpf:
  masquerade: false

ipam:
  mode: kubernetes

# Configure IPv4 native routing CIDR to match cluster pod CIDR
ipv4NativeRoutingCIDR: "10.44.0.0/16"

operator:
  replicas: 1

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: nginx-external
      hosts:
        - hubble-app.dev.kuberise.dev

cluster:
  name: dev-app-onprem-one
  id: 11 # 1 to 10 are reserved for shared clusters, 11 upwards are reserved for developer app clusters

# prometheus:
#   metricsService: true
#   enabled: true
#   port: 9962
#   serviceMonitor:
#     enabled: true

# dashboards:
#   enabled: true
#   label: grafana_dashboard
#   namespace: monitoring

tls:
  ca:
    cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGRENDQWZ5Z0F3SUJBZ0lSQUpkS2gwOGkveUpNWHZJeXE2WkhJOWN3RFFZSktvWklodmNOQVFFTEJRQXcKRkRFU01CQUdBMVVFQXhNSlEybHNhWFZ0SUVOQk1CNFhEVEkxTURNeU1ESXlNVE14TkZvWERUSTRNRE14T1RJeQpNVE14TkZvd0ZERVNNQkFHQTFVRUF4TUpRMmxzYVhWdElFTkJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUF5ZCtmTEtESzA0SFF4Zzlqcnc0blp4dkQyV1FoZnhzMmVGYUFuY2tPZ1I2dGNSN1YKaXVNdyszY0VHdTcwTHk1QUhDdXRxRW1FME1Za1Yya0l4a0dvZTdkNGdSdms1S0tna3NoTHdNV1R5QlBOeEUrZwp5aE1uNklzeFNSQiswVHpaWjRCbmJOdkdVQVlDRG5xelRvNXUvRWk4cVNublVoNjdrbjMxM2p1d3MwNXNGQUx1CmNPOFQ1bFZGL1RjZms3Z3hkcUd3dFJxSllZWW5ZbGNMNDY3Z3RjcDY2RllsSjVtdDUzWjl6YzJ1OFRzU0hkeEIKZEYrMi9NYkFodVJsemlOd3grWmhZVE0wY3NUSjJVS1Qyc0VSdDEyUU1sYUh2eHJja2RuZXlEZXpBTjhpZngzRApGY0NLTFdBTE5yU2lBY3E1bWlNcmk5Qy9NR29SRUVCZDRIY3V5UUlEQVFBQm8yRXdYekFPQmdOVkhROEJBZjhFCkJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdIUVlEVlIwT0JCWUVGRXBXUC9XVi9SbjYxZVkzcnNRa0tBS1UzTW8yTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQjdCdVFDWGtlWEZIclQwL3k3aW1zLzZQeEJVT2t0OXRYODdpMzg4SHhtZzFSN2s3K0R1ZFZ4CnpvSUFSY1ZlSitzekxoeHZpQnpBaE5KV1UrdVNpb3JoUk1jMldkRXpud2djVVIzVTcxVms5QlNJdjJUVEQ0Z2cKd1lzQkM4S1dDbUlvYWQ3M3ZvNm92TUdNNlhJdUVWbmxmMEUyQjdNalFBU0s1ZXBnMTZySHNUTkJ5Wi9Tcmk5TgpLVFVNL3JmRUtmREV3UXZIWkRpdmxkZ3JlTW5WRW8wODZPa3hqL3NTcU5halkvc3hucEpBZklmY21Tam5LRXowCm9uYSt2cmJUZXZFcjVkR1VWaHIzd0ZvMXRmY2Ntb0l1Q0hiV1dLc2JaS1JHdzhyMHlEY2ZKY2Q1N09jenc1NHkKSGViMzhYa1p5cFpITmZzdEFWditYRmZyb0RuUzhmUEwKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeWQrZkxLREswNEhReGc5anJ3NG5aeHZEMldRaGZ4czJlRmFBbmNrT2dSNnRjUjdWCml1TXcrM2NFR3U3MEx5NUFIQ3V0cUVtRTBNWWtWMmtJeGtHb2U3ZDRnUnZrNUtLZ2tzaEx3TVdUeUJQTnhFK2cKeWhNbjZJc3hTUkIrMFR6Wlo0Qm5iTnZHVUFZQ0RucXpUbzV1L0VpOHFTbm5VaDY3a24zMTNqdXdzMDVzRkFMdQpjTzhUNWxWRi9UY2ZrN2d4ZHFHd3RScUpZWVluWWxjTDQ2N2d0Y3A2NkZZbEo1bXQ1M1o5emMydThUc1NIZHhCCmRGKzIvTWJBaHVSbHppTnd4K1poWVRNMGNzVEoyVUtUMnNFUnQxMlFNbGFIdnhyY2tkbmV5RGV6QU44aWZ4M0QKRmNDS0xXQUxOclNpQWNxNW1pTXJpOUMvTUdvUkVFQmQ0SGN1eVFJREFRQUJBb0lCQUJRN29mLytrNldVUHNFRApITm9ZUUpIQWdpWWhONHcrUlh6VktxbmwwMXJVb015VUt4SHpDRjlEdy9rUkZ3ODlndlp2MkVWa0xQZ2h5OVdvCjlOU3VFdjFuVzZBUkZDVm9PVkRNMjI3VVBxWVFlaENoYkh1a1pOMFZTbGpJMnZVTXRMdC9icDVGL3IvWmdrNUMKTlFOOEdocVdEYmFrdVFjTmhuNDl1cTFON1QxalFwQWJtR1FVMlBaQ0dzakkxQmxzajRTdUwwVmlDTVViVXp1Ngp6TUx5WWlKbVZPUkpEeTZSSlBFNExIb0JrL0ZMeGpDVmNuRzR1ZTJjK2NSVmVqSldaQ0JmU04zbjNxOEtGNGZWCmhGTTU0SXlyVTdhcnFvci83YzBSR0VGam1IdStqNStBdTNUUmlYQjJWVjhubVozSHBPNEVnbW1sOHlxMXMya0QKbEJYZ2Zhc0NnWUVBOXFxaFFid01yTjV0cy9ySnY3b3NabEROdnJncHpUNXF1eWd3WnVHTDdjdEl0b2VIOTRsdwp2SlMwMlBGem1oT1hNTURTamxpdEF2UXp3b0lQQzRkZTN4N0JIZDhuQ24rWUs0bXd5QzQwTUp3WmorTFJ0NTFqClp2WVpLd3Z1Y1pNOWxTMEJ5WXk0dlFQbkVXTHR6ZWYrYmk2QisyNjY0THpRRTl4SlVjdHFMYzhDZ1lFQTBZTVoKSC9JTGE3a2R3d3IvUWhwVmZGVktTcGV4bkZreS9SeEdzM0JGWmcycHBVREFVd0lpZmZ3LzFYUkZIWlRVRjNINwpKRTBoT2pVV0MvQ2lxbmp4Zk9DYjN4V1g2N1pPU2dOZnEwSDg0U25FeTRWRXUwc3ZtcXc1S0dlTEVXWXZjUS9xCjhucWhRRVY3OGNLWEhTbDVrSG5SaWF0aWE3N0VrRGsvRmlpaDErY0NnWUFSZE5YZ3J3dytsNmN2MjRtM2xkZGEKamxGaE0rdFJhUjlvaTFtUmpsaTJ4WElwNk1HSWxTTnpWUnJQVjVjVXlsb2l5eUtiakU4Q0xJSVZPOXNRdDgzUgpBSDR1UFFLb1RZdFpXVzgzVzMyNkN2SU1Lc01vdVd5MWRxa2xVTHpaTU5CazVFQ0NJUUZaN3hMRk9qa1dIMXIwCk5UcGhydDV1MVMzc21lUmVjNFRhSlFLQmdBOWdlZFdZWkRJeDBmZGd0VDlhdzI5dXF4Y3lidnkwcDBOZ2NlZjEKazRKYitsbUFtUnoraVIyS0IvMVluVUlBakZoMEt5U003S1ZqQkEwNFNoZ003RnhuOThpMXd3S3Z6S3N0K0RXUAprRW5PVVAxRytMWnVYRDRUNmRZSFUzT2hkbFhyL3lod3k2ajE4SlRiM1U5c25kbDJ0MlJOU2RueWxHYXBiUEhwClpZZDlBb0dCQUxCcCtXdFBqUFNCYmd4MVZ4bHRmVzJMOUlWWVNCL3JMcGFtWm1ZTk00Q1Yvdnh1bXBDa1FEWUgKelBtaWR5VDRnVEpkVExDM0d5ZnNUS3FMN2daTml0RVF2cnFwdW1la1RERkVFeE1sbmVVT1hpM1ZPRTdSYm9wOQpuOUVyU0FoQndZWUVYZ3dSTVRTd0Rxb0s4bG9nY1pWcmh2MGl2N25xWGZGMXNMY1FZK0pJCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

clustermesh:
  # -- Deploy clustermesh-apiserver for clustermesh
  useAPIServer: true
  apiserver:
    service:
      type: NodePort
  config:
    # -- Enable the Clustermesh explicit configuration.
    enabled: true
    clusters:
    - name: dev-shared-onprem
      port: 32379
      # IPs are set dynamically by install.sh script
    - name: dev-app-onprem-one
      port: 32379
      # IPs are set dynamically by install.sh script
